version: "2.4"
services:
  plug:
    image: docker.package.tiredpixel.com/isoxya/isoxya-plugin-spellchecker-build:head
    volumes:
      - ./isx-plugin-spellchecker.cabal:/home/x/repo/isx-plugin-spellchecker.cabal
      - ./lib:/home/x/repo/lib
      - ./src:/home/x/repo/src
      - ./test:/home/x/repo/test
    networks:
      plug:
        aliases:
          - spellchecker.plugin.dev.isoxya.com
networks:
  plug:
    external: true
    name: isoxya_plug
